import Head from "next/head";
import { useStore } from "effector-react";
import { useContract, useProvider } from "wagmi";
import { useEffect } from "react";
import { BigNumber } from "ethers";

import { nftContract } from "@/web3/contracts";
import NftCard from "@/components/NftCard";
import { $nfts, getNftData } from "@/store/nft";

export default function Home() {
  const provider = useProvider();
  const contract = useContract({
    ...nftContract,
    signerOrProvider: provider,
  });
  const nftData = useStore($nfts);
  const tokenIds = [0, 1, 2, 3];

  const fetchTokenData = async () => {
    if (contract) {
      const result = await Promise.all(
        tokenIds.map(
          async (
            token
          ): Promise<{ tokenUri: string; owner: string; tokenId: number }> => {
            const tokenUri = await contract.tokenURI(BigNumber.from(token));
            const owner = await contract.ownerOf(BigNumber.from(token));
            return { tokenUri, owner, tokenId: token };
          }
        )
      );
      getNftData(result);
    }
  };
  useEffect(() => {
    fetchTokenData();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="relative flex items-center justify-center w-full h-full p-12 scroll-smooth">
          <div className="flex flex-col gap-4 sm:grid sm:grid-cols-2 lg:grid-cols-3">
            {nftData && nftData.length > 0 ? (
              nftData.map((data, index) => (
                <NftCard nftData={data} key={index} />
              ))
            ) : (
              <p>No Nfts to Show</p>
            )}
          </div>
        </div>
      </main>
    </>
  );
}
