import Head from "next/head";
import { Inter } from "next/font/google";
import { nftContract } from "@/web3/contracts";
import { useContract, useProvider } from "wagmi";
import { useEffect, useState } from "react";
import { BigNumber } from "ethers";
import NftCard from "@/components/NftCard";
import { formatTokenUri } from "@/utils";
import { NftIpfsData } from "@/types/nft";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const provider = useProvider();
  const contract = useContract({
    ...nftContract,
    signerOrProvider: provider,
  });
  const [nftData, setNftData] = useState<NftIpfsData[]>();
  const [tokenIds, setTokenIds] = useState<number[]>([0, 1, 2, 3]);

  const fetchTokenData = async () => {
    const res = await Promise.all(
      tokenIds.map(async (token) => {
        const uri = await contract?.tokenURI(BigNumber.from(token));
        if (uri) {
          const ipfsUri = formatTokenUri(uri);
          const res = await fetch(ipfsUri);
          return await res.json();
        }
      })
    );
    setNftData(res);
  };
  useEffect(() => {
    fetchTokenData();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="flex items-center justify-center w-screen h-screen">
          {nftData &&
            nftData.map((data, index) => (
              <NftCard nftData={data} key={index} />
            ))}
        </div>
      </main>
    </>
  );
}
